import { User, Goal, TeamMember, AuditLog, DepartmentCompletion, CheckIn } from './types'

export const mockUser: User = {
  id: 'u1',
  name: 'Sarah Johnson',
  email: 'sarah.johnson@company.com',
  role: 'employee',
  department: 'Engineering',
}

export const mockManagerUser: User = {
  id: 'u2',
  name: 'Michael Chen',
  email: 'michael.chen@company.com',
  role: 'manager',
  department: 'Engineering',
}

export const mockAdminUser: User = {
  id: 'u3',
  name: 'Emily Williams',
  email: 'emily.williams@company.com',
  role: 'admin',
  department: 'Human Resources',
}

export const thrustAreas = [
  'Revenue Growth',
  'Customer Satisfaction',
  'Operational Excellence',
  'Innovation',
  'Team Development',
  'Cost Optimization',
  'Market Expansion',
  'Quality Improvement',
]

export const mockGoals: Goal[] = [
  {
    id: 'g1',
    title: 'Increase quarterly revenue by 15%',
    description: 'Drive revenue growth through new client acquisition and upselling to existing clients.',
    thrustArea: 'Revenue Growth',
    unitOfMeasurement: 'numeric-higher-better',
    target: 15,
    weightage: 25,
    status: 'on-track',
    approvalStatus: 'approved',
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
    employeeId: 'u1',
    employeeName: 'Sarah Johnson',
  },
  {
    id: 'g2',
    title: 'Reduce customer churn rate to below 5%',
    description: 'Implement retention strategies and improve customer support response times.',
    thrustArea: 'Customer Satisfaction',
    unitOfMeasurement: 'numeric-lower-better',
    target: 5,
    weightage: 20,
    status: 'on-track',
    approvalStatus: 'approved',
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
    employeeId: 'u1',
    employeeName: 'Sarah Johnson',
  },
  {
    id: 'g3',
    title: 'Launch 3 new product features',
    description: 'Deliver planned features on the product roadmap.',
    thrustArea: 'Innovation',
    unitOfMeasurement: 'numeric-higher-better',
    target: 3,
    weightage: 20,
    status: 'completed',
    approvalStatus: 'approved',
    createdAt: '2024-01-15',
    updatedAt: '2024-03-10',
    employeeId: 'u1',
    employeeName: 'Sarah Johnson',
  },
  {
    id: 'g4',
    title: 'Complete team training program',
    description: 'Ensure all team members complete mandatory training modules.',
    thrustArea: 'Team Development',
    unitOfMeasurement: 'timeline',
    target: 100,
    weightage: 15,
    status: 'not-started',
    approvalStatus: 'approved',
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
    employeeId: 'u1',
    employeeName: 'Sarah Johnson',
  },
  {
    id: 'g5',
    title: 'Reduce operational costs by 10%',
    description: 'Identify and implement cost-saving measures across operations.',
    thrustArea: 'Cost Optimization',
    unitOfMeasurement: 'numeric-lower-better',
    target: 10,
    weightage: 20,
    status: 'on-track',
    approvalStatus: 'pending',
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
    employeeId: 'u1',
    employeeName: 'Sarah Johnson',
  },
]

export const mockTeamGoals: Goal[] = [
  ...mockGoals,
  {
    id: 'g6',
    title: 'Improve NPS score to 70+',
    description: 'Enhance customer experience to improve Net Promoter Score.',
    thrustArea: 'Customer Satisfaction',
    unitOfMeasurement: 'numeric-higher-better',
    target: 70,
    weightage: 30,
    status: 'on-track',
    approvalStatus: 'pending',
    createdAt: '2024-01-16',
    updatedAt: '2024-01-16',
    employeeId: 'u4',
    employeeName: 'David Park',
  },
  {
    id: 'g7',
    title: 'Deliver Q2 project milestones',
    description: 'Complete all scheduled deliverables for Q2.',
    thrustArea: 'Operational Excellence',
    unitOfMeasurement: 'timeline',
    target: 100,
    weightage: 25,
    status: 'on-track',
    approvalStatus: 'returned',
    createdAt: '2024-01-17',
    updatedAt: '2024-01-20',
    employeeId: 'u5',
    employeeName: 'Lisa Thompson',
  },
]

export const mockTeamMembers: TeamMember[] = [
  {
    id: 'u1',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@company.com',
    department: 'Engineering',
    goalsCount: 5,
    approvalStatus: 'approved',
    checkIns: { Q1: true, Q2: true, Q3: false, Q4: false },
  },
  {
    id: 'u4',
    name: 'David Park',
    email: 'david.park@company.com',
    department: 'Engineering',
    goalsCount: 4,
    approvalStatus: 'pending',
    checkIns: { Q1: true, Q2: false, Q3: false, Q4: false },
  },
  {
    id: 'u5',
    name: 'Lisa Thompson',
    email: 'lisa.thompson@company.com',
    department: 'Engineering',
    goalsCount: 3,
    approvalStatus: 'returned',
    checkIns: { Q1: true, Q2: true, Q3: true, Q4: false },
  },
  {
    id: 'u6',
    name: 'James Wilson',
    email: 'james.wilson@company.com',
    department: 'Engineering',
    goalsCount: 5,
    approvalStatus: 'approved',
    checkIns: { Q1: true, Q2: true, Q3: false, Q4: false },
  },
]

export const mockAuditLogs: AuditLog[] = [
  {
    id: 'a1',
    employeeId: 'u1',
    employeeName: 'Sarah Johnson',
    goalId: 'g1',
    goalTitle: 'Increase quarterly revenue by 15%',
    fieldChanged: 'Target',
    oldValue: '12%',
    newValue: '15%',
    changedBy: 'Michael Chen',
    timestamp: '2024-03-15T10:30:00Z',
  },
  {
    id: 'a2',
    employeeId: 'u4',
    employeeName: 'David Park',
    goalId: 'g6',
    goalTitle: 'Improve NPS score to 70+',
    fieldChanged: 'Status',
    oldValue: 'Not Started',
    newValue: 'On Track',
    changedBy: 'David Park',
    timestamp: '2024-03-14T14:22:00Z',
  },
  {
    id: 'a3',
    employeeId: 'u5',
    employeeName: 'Lisa Thompson',
    goalId: 'g7',
    goalTitle: 'Deliver Q2 project milestones',
    fieldChanged: 'Weightage',
    oldValue: '20%',
    newValue: '25%',
    changedBy: 'Michael Chen',
    timestamp: '2024-03-13T09:15:00Z',
  },
  {
    id: 'a4',
    employeeId: 'u1',
    employeeName: 'Sarah Johnson',
    goalId: 'g3',
    goalTitle: 'Launch 3 new product features',
    fieldChanged: 'Status',
    oldValue: 'On Track',
    newValue: 'Completed',
    changedBy: 'Sarah Johnson',
    timestamp: '2024-03-10T16:45:00Z',
  },
  {
    id: 'a5',
    employeeId: 'u6',
    employeeName: 'James Wilson',
    goalId: 'g8',
    goalTitle: 'Optimize database performance',
    fieldChanged: 'Description',
    oldValue: 'Improve query times',
    newValue: 'Improve query times and reduce server load by 30%',
    changedBy: 'James Wilson',
    timestamp: '2024-03-09T11:30:00Z',
  },
]

export const mockDepartmentCompletion: DepartmentCompletion[] = [
  { department: 'Engineering', Q1: 95, Q2: 88, Q3: 45, Q4: 0 },
  { department: 'Sales', Q1: 100, Q2: 92, Q3: 60, Q4: 0 },
  { department: 'Marketing', Q1: 90, Q2: 85, Q3: 30, Q4: 0 },
  { department: 'HR', Q1: 100, Q2: 100, Q3: 80, Q4: 0 },
  { department: 'Finance', Q1: 88, Q2: 78, Q3: 25, Q4: 0 },
  { department: 'Operations', Q1: 92, Q2: 90, Q3: 55, Q4: 0 },
]

export const mockEmployees = [
  { id: 'u1', name: 'Sarah Johnson', department: 'Engineering' },
  { id: 'u4', name: 'David Park', department: 'Engineering' },
  { id: 'u5', name: 'Lisa Thompson', department: 'Engineering' },
  { id: 'u6', name: 'James Wilson', department: 'Engineering' },
  { id: 'u7', name: 'Amanda Garcia', department: 'Sales' },
  { id: 'u8', name: 'Robert Martinez', department: 'Sales' },
  { id: 'u9', name: 'Jennifer Brown', department: 'Marketing' },
  { id: 'u10', name: 'Christopher Lee', department: 'Marketing' },
]

export const mockCheckIns: CheckIn[] = [
  {
    id: 'c1',
    goalId: 'g1',
    quarter: 'Q1',
    plannedTarget: 15,
    actualAchievement: 12,
    status: 'on-track',
    score: 80,
    submittedAt: '2024-03-31',
  },
  {
    id: 'c2',
    goalId: 'g2',
    quarter: 'Q1',
    plannedTarget: 5,
    actualAchievement: 4.5,
    status: 'completed',
    score: 110,
    submittedAt: '2024-03-31',
  },
  {
    id: 'c3',
    goalId: 'g3',
    quarter: 'Q1',
    plannedTarget: 3,
    actualAchievement: 3,
    status: 'completed',
    score: 100,
    submittedAt: '2024-03-31',
  },
  {
    id: 'c4',
    goalId: 'g4',
    quarter: 'Q1',
    plannedTarget: 100,
    actualAchievement: null,
    status: 'not-started',
    score: null,
    submittedAt: null,
  },
  {
    id: 'c5',
    goalId: 'g5',
    quarter: 'Q1',
    plannedTarget: 10,
    actualAchievement: 8,
    status: 'on-track',
    score: 80,
    submittedAt: '2024-03-31',
  },
]
