import { 
  User, 
  Goal, 
  TeamMember, 
  AuditLog, 
  DepartmentCompletion, 
  CheckIn, 
  GoalSheet, 
  GoalCycle, 
  Escalation, 
  SharedGoal, 
  ActivityLog,
  Report
} from './types'

// ============================================
// USERS - Indian/Corporate Names
// ============================================

export const mockEmployeeUser: User = {
  id: 'u1',
  name: 'Priya Sharma',
  email: 'priya.sharma@alignos.com',
  role: 'employee',
  department: 'Engineering',
  managerId: 'u2',
  managerName: 'Rohan Mehta',
}

export const mockManagerUser: User = {
  id: 'u2',
  name: 'Rohan Mehta',
  email: 'rohan.mehta@alignos.com',
  role: 'manager',
  department: 'Engineering',
}

export const mockAdminUser: User = {
  id: 'u3',
  name: 'Anika Verma',
  email: 'anika.verma@alignos.com',
  role: 'admin',
  department: 'Human Resources',
}

// ============================================
// THRUST AREAS
// ============================================

export const thrustAreas = [
  'Customer Success',
  'Operational Excellence',
  'Innovation',
  'People & Culture',
  'Financial Performance',
  'Revenue Growth',
  'Cost Optimization',
  'Quality Improvement',
]

// ============================================
// DEPARTMENTS
// ============================================

export const departments = [
  'Engineering',
  'Product',
  'Sales',
  'Customer Success',
  'Finance',
  'Human Resources',
  'Operations',
  'Marketing',
]

// ============================================
// GOAL CYCLE
// ============================================

export const mockGoalCycle: GoalCycle = {
  id: 'cycle-fy26',
  name: 'FY26 Goal Cycle',
  year: 2026,
  startDate: '2025-04-01',
  endDate: '2026-03-31',
  status: 'active',
  windows: {
    goalCreation: { start: '2025-05-01', end: '2025-05-31' },
    q1CheckIn: { start: '2025-07-01', end: '2025-07-15' },
    q2CheckIn: { start: '2025-10-01', end: '2025-10-15' },
    q3CheckIn: { start: '2026-01-01', end: '2026-01-15' },
    q4CheckIn: { start: '2026-03-15', end: '2026-03-31' },
  },
}

// ============================================
// GOAL SHEETS
// ============================================

export const mockGoalSheet: GoalSheet = {
  id: 'gs1',
  employeeId: 'u1',
  employeeName: 'Priya Sharma',
  department: 'Engineering',
  managerId: 'u2',
  managerName: 'Rohan Mehta',
  cycleId: 'cycle-fy26',
  cycleName: 'FY26 Goal Cycle',
  status: 'approved',
  totalWeightage: 100,
  goalsCount: 5,
  submittedAt: '2025-05-15T10:30:00Z',
  approvedAt: '2025-05-18T14:22:00Z',
  approvedBy: 'Rohan Mehta',
  managerComments: 'Well-structured goals aligned with team objectives. Approved.',
  lastUpdated: '2025-05-18T14:22:00Z',
}

// ============================================
// GOALS - Priya's Goals
// ============================================

export const mockGoals: Goal[] = [
  {
    id: 'g1',
    title: 'Deliver API Performance Optimization Initiative',
    description: 'Improve API response times by 40% through caching, query optimization, and infrastructure upgrades.',
    thrustArea: 'Operational Excellence',
    unitOfMeasurement: 'percentage',
    target: 40,
    weightage: 25,
    status: 'on-track',
    approvalStatus: 'approved',
    isLocked: true,
    progress: 56,
    actualAchievement: 22,
    createdAt: '2025-05-10',
    updatedAt: '2025-10-15',
    employeeId: 'u1',
    employeeName: 'Priya Sharma',
  },
  {
    id: 'g2',
    title: 'Reduce Production Incidents by 50%',
    description: 'Implement proactive monitoring, automated alerts, and runbook automation to minimize production issues.',
    thrustArea: 'Operational Excellence',
    unitOfMeasurement: 'numeric-lower-better',
    target: 10,
    weightage: 20,
    status: 'on-track',
    approvalStatus: 'approved',
    isLocked: true,
    progress: 65,
    actualAchievement: 7,
    createdAt: '2025-05-10',
    updatedAt: '2025-10-15',
    employeeId: 'u1',
    employeeName: 'Priya Sharma',
  },
  {
    id: 'g3',
    title: 'Launch Customer Self-Service Portal',
    description: 'Build and deploy a customer-facing portal for self-service support, reducing ticket volume.',
    thrustArea: 'Customer Success',
    unitOfMeasurement: 'timeline',
    target: 100,
    weightage: 20,
    status: 'completed',
    approvalStatus: 'approved',
    isLocked: true,
    progress: 100,
    actualAchievement: 100,
    createdAt: '2025-05-10',
    updatedAt: '2025-09-30',
    employeeId: 'u1',
    employeeName: 'Priya Sharma',
  },
  {
    id: 'g4',
    title: 'Implement CI/CD Pipeline Improvements',
    description: 'Reduce deployment time by 60% through pipeline optimization and parallel test execution.',
    thrustArea: 'Innovation',
    unitOfMeasurement: 'percentage',
    target: 60,
    weightage: 20,
    status: 'on-track',
    approvalStatus: 'approved',
    isLocked: true,
    progress: 45,
    actualAchievement: 27,
    createdAt: '2025-05-10',
    updatedAt: '2025-10-15',
    employeeId: 'u1',
    employeeName: 'Priya Sharma',
  },
  {
    id: 'g5',
    title: 'Complete Cloud Architecture Certification',
    description: 'Achieve AWS Solutions Architect Professional certification to enhance team cloud capabilities.',
    thrustArea: 'People & Culture',
    unitOfMeasurement: 'zero-based',
    target: 1,
    weightage: 15,
    status: 'not-started',
    approvalStatus: 'approved',
    isLocked: true,
    isShared: true,
    progress: 0,
    createdAt: '2025-05-10',
    updatedAt: '2025-05-18',
    employeeId: 'u1',
    employeeName: 'Priya Sharma',
  },
]

// ============================================
// TEAM GOALS - Manager View
// ============================================

export const mockTeamGoals: Goal[] = [
  ...mockGoals,
  {
    id: 'g6',
    title: 'Achieve Customer NPS Score of 75+',
    description: 'Improve customer satisfaction through enhanced support processes and proactive engagement.',
    thrustArea: 'Customer Success',
    unitOfMeasurement: 'numeric-higher-better',
    target: 75,
    weightage: 30,
    status: 'on-track',
    approvalStatus: 'pending',
    progress: 68,
    actualAchievement: 68,
    createdAt: '2025-05-16',
    updatedAt: '2025-05-16',
    employeeId: 'u4',
    employeeName: 'Karthik Iyer',
  },
  {
    id: 'g7',
    title: 'Deliver Q2 Product Roadmap Milestones',
    description: 'Complete all scheduled feature deliverables for Q2 product roadmap.',
    thrustArea: 'Operational Excellence',
    unitOfMeasurement: 'timeline',
    target: 100,
    weightage: 25,
    status: 'on-track',
    approvalStatus: 'returned',
    progress: 40,
    createdAt: '2025-05-17',
    updatedAt: '2025-05-20',
    employeeId: 'u5',
    employeeName: 'Megha Nair',
  },
  {
    id: 'g8',
    title: 'Reduce Customer Churn Rate to Below 5%',
    description: 'Implement retention strategies and proactive customer success initiatives.',
    thrustArea: 'Revenue Growth',
    unitOfMeasurement: 'numeric-lower-better',
    target: 5,
    weightage: 25,
    status: 'on-track',
    approvalStatus: 'approved',
    isLocked: true,
    progress: 72,
    actualAchievement: 4.2,
    createdAt: '2025-05-12',
    updatedAt: '2025-10-15',
    employeeId: 'u6',
    employeeName: 'Daniel Cruz',
  },
]

// ============================================
// TEAM MEMBERS
// ============================================

export const mockTeamMembers: TeamMember[] = [
  {
    id: 'u1',
    name: 'Priya Sharma',
    email: 'priya.sharma@alignos.com',
    department: 'Engineering',
    goalsCount: 5,
    totalWeightage: 100,
    sheetStatus: 'locked',
    approvalStatus: 'approved',
    averageAchievement: 56,
    checkIns: { Q1: true, Q2: true, Q3: true, Q4: false },
  },
  {
    id: 'u4',
    name: 'Karthik Iyer',
    email: 'karthik.iyer@alignos.com',
    department: 'Engineering',
    goalsCount: 4,
    totalWeightage: 100,
    sheetStatus: 'pending-approval',
    approvalStatus: 'pending',
    averageAchievement: 62,
    checkIns: { Q1: true, Q2: true, Q3: false, Q4: false },
  },
  {
    id: 'u5',
    name: 'Megha Nair',
    email: 'megha.nair@alignos.com',
    department: 'Engineering',
    goalsCount: 3,
    totalWeightage: 85,
    sheetStatus: 'returned',
    approvalStatus: 'returned',
    averageAchievement: 45,
    checkIns: { Q1: true, Q2: true, Q3: true, Q4: false },
  },
  {
    id: 'u6',
    name: 'Daniel Cruz',
    email: 'daniel.cruz@alignos.com',
    department: 'Engineering',
    goalsCount: 5,
    totalWeightage: 100,
    sheetStatus: 'locked',
    approvalStatus: 'approved',
    averageAchievement: 72,
    checkIns: { Q1: true, Q2: true, Q3: true, Q4: false },
  },
  {
    id: 'u7',
    name: 'Lina Park',
    email: 'lina.park@alignos.com',
    department: 'Engineering',
    goalsCount: 5,
    totalWeightage: 100,
    sheetStatus: 'locked',
    approvalStatus: 'approved',
    averageAchievement: 58,
    checkIns: { Q1: true, Q2: true, Q3: false, Q4: false },
  },
  {
    id: 'u8',
    name: 'Arjun Patel',
    email: 'arjun.patel@alignos.com',
    department: 'Engineering',
    goalsCount: 4,
    totalWeightage: 100,
    sheetStatus: 'draft',
    approvalStatus: 'draft',
    averageAchievement: 0,
    checkIns: { Q1: false, Q2: false, Q3: false, Q4: false },
  },
  {
    id: 'u9',
    name: 'Sneha Reddy',
    email: 'sneha.reddy@alignos.com',
    department: 'Engineering',
    goalsCount: 5,
    totalWeightage: 100,
    sheetStatus: 'locked',
    approvalStatus: 'approved',
    averageAchievement: 68,
    checkIns: { Q1: true, Q2: true, Q3: true, Q4: false },
  },
  {
    id: 'u10',
    name: 'Vikram Singh',
    email: 'vikram.singh@alignos.com',
    department: 'Engineering',
    goalsCount: 5,
    totalWeightage: 100,
    sheetStatus: 'locked',
    approvalStatus: 'approved',
    averageAchievement: 55,
    checkIns: { Q1: true, Q2: true, Q3: false, Q4: false },
  },
]

// ============================================
// AUDIT LOGS
// ============================================

export const mockAuditLogs: AuditLog[] = [
  {
    id: 'a1',
    auditId: 'AUD-2025-0001',
    employeeId: 'u1',
    employeeName: 'Priya Sharma',
    goalId: 'g1',
    goalTitle: 'Deliver API Performance Optimization Initiative',
    fieldChanged: 'Q3 Achievement',
    oldValue: '18%',
    newValue: '22%',
    changedBy: 'Priya Sharma',
    changedByRole: 'employee',
    actionType: 'update',
    timestamp: '2025-10-15T10:30:00Z',
  },
  {
    id: 'a2',
    auditId: 'AUD-2025-0002',
    employeeId: 'u4',
    employeeName: 'Karthik Iyer',
    goalId: 'g6',
    goalTitle: 'Achieve Customer NPS Score of 75+',
    fieldChanged: 'Status',
    oldValue: 'Pending',
    newValue: 'Submitted',
    changedBy: 'Karthik Iyer',
    changedByRole: 'employee',
    actionType: 'submit',
    timestamp: '2025-10-14T14:22:00Z',
  },
  {
    id: 'a3',
    auditId: 'AUD-2025-0003',
    employeeId: 'u5',
    employeeName: 'Megha Nair',
    goalId: 'g7',
    goalTitle: 'Deliver Q2 Product Roadmap Milestones',
    fieldChanged: 'Approval Status',
    oldValue: 'Pending',
    newValue: 'Returned',
    changedBy: 'Rohan Mehta',
    changedByRole: 'manager',
    actionType: 'return',
    timestamp: '2025-10-13T09:15:00Z',
  },
  {
    id: 'a4',
    auditId: 'AUD-2025-0004',
    employeeId: 'u1',
    employeeName: 'Priya Sharma',
    goalId: 'g3',
    goalTitle: 'Launch Customer Self-Service Portal',
    fieldChanged: 'Status',
    oldValue: 'On Track',
    newValue: 'Completed',
    changedBy: 'Priya Sharma',
    changedByRole: 'employee',
    actionType: 'update',
    timestamp: '2025-09-30T16:45:00Z',
  },
  {
    id: 'a5',
    auditId: 'AUD-2025-0005',
    employeeId: 'u6',
    employeeName: 'Daniel Cruz',
    goalId: 'g8',
    goalTitle: 'Reduce Customer Churn Rate to Below 5%',
    fieldChanged: 'Weightage',
    oldValue: '20%',
    newValue: '25%',
    changedBy: 'Rohan Mehta',
    changedByRole: 'manager',
    actionType: 'update',
    timestamp: '2025-10-09T11:30:00Z',
  },
  {
    id: 'a6',
    auditId: 'AUD-2025-0006',
    employeeId: 'u1',
    employeeName: 'Priya Sharma',
    goalId: 'gs1',
    goalTitle: 'Goal Sheet FY26',
    fieldChanged: 'Sheet Status',
    oldValue: 'Approved',
    newValue: 'Locked',
    changedBy: 'System',
    changedByRole: 'admin',
    actionType: 'approve',
    timestamp: '2025-05-18T14:25:00Z',
  },
  {
    id: 'a7',
    auditId: 'AUD-2025-0007',
    employeeId: 'u7',
    employeeName: 'Lina Park',
    goalId: 'g9',
    goalTitle: 'Implement Data Analytics Dashboard',
    fieldChanged: 'Target',
    oldValue: '3 dashboards',
    newValue: '5 dashboards',
    changedBy: 'Rohan Mehta',
    changedByRole: 'manager',
    actionType: 'update',
    timestamp: '2025-10-08T09:00:00Z',
  },
  {
    id: 'a8',
    auditId: 'AUD-2025-0008',
    employeeId: 'u9',
    employeeName: 'Sneha Reddy',
    goalId: 'g10',
    goalTitle: 'Complete Security Compliance Audit',
    fieldChanged: 'Q2 Achievement',
    oldValue: '60%',
    newValue: '85%',
    changedBy: 'Sneha Reddy',
    changedByRole: 'employee',
    actionType: 'update',
    timestamp: '2025-10-07T15:30:00Z',
  },
]

// ============================================
// DEPARTMENT COMPLETION
// ============================================

export const mockDepartmentCompletion: DepartmentCompletion[] = [
  { department: 'Engineering', totalEmployees: 45, sheetsLocked: 38, Q1: 95, Q2: 88, Q3: 72, Q4: 0 },
  { department: 'Product', totalEmployees: 22, sheetsLocked: 20, Q1: 100, Q2: 92, Q3: 78, Q4: 0 },
  { department: 'Sales', totalEmployees: 85, sheetsLocked: 72, Q1: 98, Q2: 85, Q3: 65, Q4: 0 },
  { department: 'Customer Success', totalEmployees: 35, sheetsLocked: 32, Q1: 100, Q2: 95, Q3: 82, Q4: 0 },
  { department: 'Finance', totalEmployees: 18, sheetsLocked: 18, Q1: 100, Q2: 100, Q3: 88, Q4: 0 },
  { department: 'Human Resources', totalEmployees: 12, sheetsLocked: 12, Q1: 100, Q2: 100, Q3: 92, Q4: 0 },
  { department: 'Operations', totalEmployees: 28, sheetsLocked: 25, Q1: 92, Q2: 90, Q3: 68, Q4: 0 },
  { department: 'Marketing', totalEmployees: 30, sheetsLocked: 26, Q1: 96, Q2: 88, Q3: 58, Q4: 0 },
]

// ============================================
// ALL EMPLOYEES (for Admin)
// ============================================

export const mockEmployees = [
  { id: 'u1', name: 'Priya Sharma', email: 'priya.sharma@alignos.com', department: 'Engineering', managerId: 'u2', managerName: 'Rohan Mehta' },
  { id: 'u4', name: 'Karthik Iyer', email: 'karthik.iyer@alignos.com', department: 'Engineering', managerId: 'u2', managerName: 'Rohan Mehta' },
  { id: 'u5', name: 'Megha Nair', email: 'megha.nair@alignos.com', department: 'Engineering', managerId: 'u2', managerName: 'Rohan Mehta' },
  { id: 'u6', name: 'Daniel Cruz', email: 'daniel.cruz@alignos.com', department: 'Engineering', managerId: 'u2', managerName: 'Rohan Mehta' },
  { id: 'u7', name: 'Lina Park', email: 'lina.park@alignos.com', department: 'Engineering', managerId: 'u2', managerName: 'Rohan Mehta' },
  { id: 'u8', name: 'Arjun Patel', email: 'arjun.patel@alignos.com', department: 'Engineering', managerId: 'u2', managerName: 'Rohan Mehta' },
  { id: 'u9', name: 'Sneha Reddy', email: 'sneha.reddy@alignos.com', department: 'Engineering', managerId: 'u2', managerName: 'Rohan Mehta' },
  { id: 'u10', name: 'Vikram Singh', email: 'vikram.singh@alignos.com', department: 'Engineering', managerId: 'u2', managerName: 'Rohan Mehta' },
  { id: 'u11', name: 'Ananya Desai', email: 'ananya.desai@alignos.com', department: 'Product', managerId: 'u12', managerName: 'Raj Kumar' },
  { id: 'u13', name: 'Neha Gupta', email: 'neha.gupta@alignos.com', department: 'Sales', managerId: 'u14', managerName: 'Amit Shah' },
  { id: 'u15', name: 'Rahul Joshi', email: 'rahul.joshi@alignos.com', department: 'Customer Success', managerId: 'u16', managerName: 'Kavita Menon' },
  { id: 'u17', name: 'Divya Krishnan', email: 'divya.krishnan@alignos.com', department: 'Finance', managerId: 'u18', managerName: 'Suresh Pillai' },
]

// ============================================
// CHECK-INS
// ============================================

export const mockCheckIns: CheckIn[] = [
  {
    id: 'c1',
    goalId: 'g1',
    goalTitle: 'Deliver API Performance Optimization Initiative',
    quarter: 'Q3',
    plannedTarget: 40,
    actualAchievement: 22,
    unitOfMeasurement: 'percentage',
    status: 'on-track',
    score: 55,
    managerComment: 'Good progress. Focus on caching improvements in Q4.',
    submittedAt: '2025-10-15T10:30:00Z',
  },
  {
    id: 'c2',
    goalId: 'g2',
    goalTitle: 'Reduce Production Incidents by 50%',
    quarter: 'Q3',
    plannedTarget: 10,
    actualAchievement: 7,
    unitOfMeasurement: 'numeric-lower-better',
    status: 'on-track',
    score: 143,
    managerComment: 'Excellent progress! Already exceeding target.',
    submittedAt: '2025-10-15T10:35:00Z',
  },
  {
    id: 'c3',
    goalId: 'g3',
    goalTitle: 'Launch Customer Self-Service Portal',
    quarter: 'Q3',
    plannedTarget: 100,
    actualAchievement: 100,
    unitOfMeasurement: 'timeline',
    status: 'completed',
    score: 100,
    managerComment: 'Completed ahead of schedule. Great work!',
    submittedAt: '2025-09-30T16:45:00Z',
  },
  {
    id: 'c4',
    goalId: 'g4',
    goalTitle: 'Implement CI/CD Pipeline Improvements',
    quarter: 'Q3',
    plannedTarget: 60,
    actualAchievement: 27,
    unitOfMeasurement: 'percentage',
    status: 'on-track',
    score: 45,
    managerComment: 'On track. Consider parallel test execution for Q4.',
    submittedAt: '2025-10-15T10:40:00Z',
  },
  {
    id: 'c5',
    goalId: 'g5',
    goalTitle: 'Complete Cloud Architecture Certification',
    quarter: 'Q3',
    plannedTarget: 1,
    actualAchievement: null,
    unitOfMeasurement: 'zero-based',
    status: 'not-started',
    score: null,
    submittedAt: null,
  },
]

// ============================================
// ESCALATIONS
// ============================================

export const mockEscalations: Escalation[] = [
  {
    id: 'e1',
    type: 'goal-not-submitted',
    employeeId: 'u8',
    employeeName: 'Arjun Patel',
    managerId: 'u2',
    managerName: 'Rohan Mehta',
    department: 'Engineering',
    severity: 'high',
    message: 'Goal sheet not submitted for FY26 cycle',
    daysOverdue: 12,
    escalationLevel: 'manager',
    dueDate: '2025-10-01',
    createdAt: '2025-10-13T00:00:00Z',
  },
  {
    id: 'e2',
    type: 'checkin-pending',
    employeeId: 'u5',
    employeeName: 'Megha Nair',
    managerId: 'u2',
    managerName: 'Rohan Mehta',
    department: 'Engineering',
    severity: 'medium',
    message: 'Q3 check-in not submitted within active window',
    daysOverdue: 5,
    escalationLevel: 'employee',
    dueDate: '2025-10-15',
    createdAt: '2025-10-20T00:00:00Z',
  },
  {
    id: 'e3',
    type: 'approval-overdue',
    employeeId: 'u4',
    employeeName: 'Karthik Iyer',
    managerId: 'u2',
    managerName: 'Rohan Mehta',
    department: 'Engineering',
    severity: 'medium',
    message: 'Manager approval pending for 8 days',
    daysOverdue: 8,
    escalationLevel: 'skip-level',
    dueDate: '2025-10-12',
    createdAt: '2025-10-20T00:00:00Z',
  },
  {
    id: 'e4',
    type: 'weightage-mismatch',
    employeeId: 'u5',
    employeeName: 'Megha Nair',
    managerId: 'u2',
    managerName: 'Rohan Mehta',
    department: 'Engineering',
    severity: 'low',
    message: 'Goal sheet weightage does not equal 100% (currently 85%)',
    daysOverdue: 0,
    escalationLevel: 'employee',
    dueDate: '2025-10-25',
    createdAt: '2025-10-18T00:00:00Z',
  },
]

// ============================================
// SHARED GOALS
// ============================================

export const mockSharedGoals: SharedGoal[] = [
  {
    id: 'sg1',
    title: 'Complete Cloud Architecture Certification',
    description: 'All team members to achieve AWS Solutions Architect certification.',
    thrustArea: 'People & Culture',
    target: 1,
    unitOfMeasurement: 'zero-based',
    primaryOwnerId: 'u2',
    primaryOwnerName: 'Rohan Mehta',
    linkedEmployees: [
      { id: 'u1', name: 'Priya Sharma', department: 'Engineering' },
      { id: 'u4', name: 'Karthik Iyer', department: 'Engineering' },
      { id: 'u6', name: 'Daniel Cruz', department: 'Engineering' },
      { id: 'u7', name: 'Lina Park', department: 'Engineering' },
    ],
    syncedAchievement: 25,
    status: 'active',
    createdAt: '2025-05-01T00:00:00Z',
    createdBy: 'Rohan Mehta',
  },
  {
    id: 'sg2',
    title: 'Achieve Department NPS of 80+',
    description: 'Cross-functional initiative to improve internal customer satisfaction.',
    thrustArea: 'Customer Success',
    target: 80,
    unitOfMeasurement: 'numeric-higher-better',
    primaryOwnerId: 'u3',
    primaryOwnerName: 'Anika Verma',
    linkedEmployees: [
      { id: 'u15', name: 'Rahul Joshi', department: 'Customer Success' },
      { id: 'u13', name: 'Neha Gupta', department: 'Sales' },
      { id: 'u11', name: 'Ananya Desai', department: 'Product' },
    ],
    syncedAchievement: 72,
    status: 'active',
    createdAt: '2025-05-05T00:00:00Z',
    createdBy: 'Anika Verma',
  },
  {
    id: 'sg3',
    title: 'Complete Mandatory Compliance Training',
    description: 'All employees must complete annual compliance and security training.',
    thrustArea: 'Operational Excellence',
    target: 100,
    unitOfMeasurement: 'percentage',
    primaryOwnerId: 'u3',
    primaryOwnerName: 'Anika Verma',
    linkedEmployees: mockEmployees.map(e => ({ id: e.id, name: e.name, department: e.department })),
    syncedAchievement: 85,
    status: 'locked',
    createdAt: '2025-04-15T00:00:00Z',
    createdBy: 'Anika Verma',
  },
]

// ============================================
// ACTIVITY LOGS
// ============================================

export const mockActivityLogs: ActivityLog[] = [
  {
    id: 'act1',
    type: 'goal-approved',
    actorId: 'u2',
    actorName: 'Rohan Mehta',
    actorRole: 'manager',
    targetId: 'gs1',
    targetName: 'Priya Sharma',
    description: 'Goal sheet approved and locked',
    timestamp: '2025-05-18T14:22:00Z',
  },
  {
    id: 'act2',
    type: 'checkin-submitted',
    actorId: 'u1',
    actorName: 'Priya Sharma',
    actorRole: 'employee',
    targetId: 'g1',
    targetName: 'API Performance Optimization',
    description: 'Q3 check-in submitted',
    timestamp: '2025-10-15T10:30:00Z',
  },
  {
    id: 'act3',
    type: 'goal-returned',
    actorId: 'u2',
    actorName: 'Rohan Mehta',
    actorRole: 'manager',
    targetId: 'g7',
    targetName: 'Megha Nair',
    description: 'Goal sheet returned for rework - weightage adjustment needed',
    timestamp: '2025-10-13T09:15:00Z',
  },
  {
    id: 'act4',
    type: 'shared-goal-pushed',
    actorId: 'u3',
    actorName: 'Anika Verma',
    actorRole: 'admin',
    targetId: 'sg3',
    targetName: 'Compliance Training',
    description: 'Shared goal pushed to all employees',
    timestamp: '2025-04-15T10:00:00Z',
  },
  {
    id: 'act5',
    type: 'comment-added',
    actorId: 'u2',
    actorName: 'Rohan Mehta',
    actorRole: 'manager',
    targetId: 'c1',
    targetName: 'Priya Sharma - Q3 Check-in',
    description: 'Manager comment added on Q3 check-in',
    timestamp: '2025-10-16T11:00:00Z',
  },
]

// ============================================
// REPORTS DATA
// ============================================

export const mockReportData: Report[] = [
  {
    employeeId: 'u1',
    employeeName: 'Priya Sharma',
    department: 'Engineering',
    managerName: 'Rohan Mehta',
    goalTitle: 'Deliver API Performance Optimization Initiative',
    thrustArea: 'Operational Excellence',
    plannedTarget: 40,
    actualAchievement: 22,
    weightage: 25,
    score: 55,
    quarter: 'Q3',
    status: 'on-track',
  },
  {
    employeeId: 'u1',
    employeeName: 'Priya Sharma',
    department: 'Engineering',
    managerName: 'Rohan Mehta',
    goalTitle: 'Reduce Production Incidents by 50%',
    thrustArea: 'Operational Excellence',
    plannedTarget: 10,
    actualAchievement: 7,
    weightage: 20,
    score: 143,
    quarter: 'Q3',
    status: 'on-track',
  },
  {
    employeeId: 'u1',
    employeeName: 'Priya Sharma',
    department: 'Engineering',
    managerName: 'Rohan Mehta',
    goalTitle: 'Launch Customer Self-Service Portal',
    thrustArea: 'Customer Success',
    plannedTarget: 100,
    actualAchievement: 100,
    weightage: 20,
    score: 100,
    quarter: 'Q3',
    status: 'completed',
  },
  {
    employeeId: 'u6',
    employeeName: 'Daniel Cruz',
    department: 'Engineering',
    managerName: 'Rohan Mehta',
    goalTitle: 'Reduce Customer Churn Rate to Below 5%',
    thrustArea: 'Revenue Growth',
    plannedTarget: 5,
    actualAchievement: 4.2,
    weightage: 25,
    score: 119,
    quarter: 'Q3',
    status: 'on-track',
  },
  {
    employeeId: 'u4',
    employeeName: 'Karthik Iyer',
    department: 'Engineering',
    managerName: 'Rohan Mehta',
    goalTitle: 'Achieve Customer NPS Score of 75+',
    thrustArea: 'Customer Success',
    plannedTarget: 75,
    actualAchievement: 68,
    weightage: 30,
    score: 91,
    quarter: 'Q3',
    status: 'on-track',
  },
]

// Legacy exports for backwards compatibility
export const mockUser = mockEmployeeUser
